### ISSUE TITLE
Icon for Helipad

### ISSUE THREAD

**Issue by daveajones** [ibz/mureader#10]
Do you have an icon I can use to represent usocial.me in Helipad boost display?

**Comment by daveajones** [comment]
Here is what the UI looks like:  [https://twitter.com/getumbrel/status/1483070058515804161/photo/1](https://twitter.com/getumbrel/status/1483070058515804161/photo/1)

**Comment by ibz** [comment]
Sure, I'll make one!

What format would you like?

**Comment by daveajones** [comment]
Png would be great.

**Comment by ibz** [comment]
![mu](https://user-images.githubusercontent.com/111120/152137204-e90f1b66-6dca-40b5-adaf-45dd78e9bd64.png)

**Comment by ibz** [comment]
BTW, I changed the name reported in the TLV to "usocial".

**Comment by daveajones** [comment]
10-4. Thanks!
