### ISSUE TITLE
Bug: Blog links are relative on Umbrel 

### ISSUE THREAD

**Issue by KayBeSee** [ibz/mureader#14]
When clicking a blog link, I am getting sent to `http://umbrel.local:8448/some/blog/post/params` instead of `https://blogwebsite.com/some/blog/post/params` when accessing on Umbrel.

**Comment by ibz** [comment]
Would you mind sharing the URL of that particular blog/feed?

Or could you confirm that the item links in that feed are relative?

I just want to make sure I nail this. It definitely works for absolute URLs.

**Comment by KayBeSee** [comment]
The URL I was using was
https://kevinmulcrone.com/music/2021/07/07/tommy-edwards.html
